<?xml version="1.0"?>
<robot xmlns:xacro="http://www.ros.org/wiki/xacro">

    <xacro:property name="camera_length" value="0.01" />
    <xacro:property name="camera_width" value="0.1" />
    <xacro:property name="camera_height" value="0.05" />
    
    <link name="camera">
        <visual>
            <geometry>
                <box size="${camera_length} ${camera_width} ${camera_height}" />
                <origin xyz="0 0 0" rpy="0 0 0" />
            </geometry>
            <material name="black"/>
        </visual>
        <collision>
            <geometry>
                <box size="${camera_length} ${camera_width} ${camera_height}" />
                <origin xyz="0 0 0" rpy="0 0 0" />
            </geometry>
        </collision>
        <xacro:box_inertial m="0.2" l="${camera_length}" w="${camera_width}" h="${camera_height}" xyz="0 0 0" rpy="0 0 0" />
    </link>

    <joint name="base_camera" type="fixed" >
        <parent link="main_base" />
        <child link="camera" />
        <origin xyz="${0.5*(main_base_length+camera_length)} 0 0" rpy="0 0 0" />
    </joint>
</robot>