<?xml version="1.0"?>
<robot xmlns:xacro="http://www.ros.org/wiki/xacro">
    <!-- part Specifications -->
    <xacro:property name="main_base_length" value="0.6" />
    <xacro:property name="main_base_width" value="0.4" />
    <xacro:property name="main_base_height" value="0.2" />
    <xacro:property name="wheel_radius" value="0.1" />
    <xacro:property name="wheel_length" value="0.05" />
    <xacro:property name="caster_wheel_radius" value="0.05" />
    <xacro:include filename="common_properties.xacro" />

    <link name="base_footprint" />
    <link name="main_base">
        <visual>
            <geometry>
                <box size="${main_base_length} ${main_base_width} ${main_base_height}" />
            </geometry>
            <origin xyz="0 0 0" rpy="0 0 0" />
            <material name="blue" />
        </visual>
        <collision>
            <geometry>
                <box size="${main_base_length} ${main_base_width} ${main_base_height}" />
            </geometry>
            <origin xyz="0 0 0" rpy="0 0 0" />
        </collision>
        <xacro:box_inertial m="0.6" l="${main_base_length}" w="${main_base_width}" h="${main_base_height}" xyz="0 0 0" rpy="0 0 0" />
    </link>
    <joint name="main_base_footprint" type="fixed">
        <parent link="base_footprint" />
        <child link="main_base" />
        <origin xyz="0 0 ${0.5*main_base_height+wheel_radius}" rpy="0 0 0" />
    </joint>

    <link name="caster_wheel_link">
        <visual>
            <geometry>
                <sphere radius="${caster_wheel_radius}" />
            </geometry>
            <origin xyz="0 0 0" rpy="0 0 0" />
            <material name="grey" />
        </visual>

        <xacro:sphere_inertial m="0.1" r="${caster_wheel_radius}"
                               xyz="0 0 0" rpy="0 0 0" />

        <collision >
            <geometry>
                <sphere radius="${caster_wheel_radius}" />
                </geometry>
            <origin xyz="0 0 0" rpy="0 0 0" />            
        </collision>
    </link>
    <joint name="base_caster_wheel_joint" type="fixed">
        <parent link="main_base" />
        <child link="caster_wheel_link" />
        <origin xyz="${0.4*main_base_length} 0 ${-(caster_wheel_radius+0.5*main_base_height)}" rpy="0 0 0" />
    </joint>

    <xacro:wheel_link prefix="left" x="-1" y="1" />
    <xacro:wheel_link prefix="right" x="-1" y="-1" />

    <xacro:include filename="camera.xacro" />
    <xacro:include filename="robot_arm.xacro" />

</robot>