<?xml version="1.0"?>
<robot xmlns:xacro="http://www.ros.org/wiki/xacro">
  <gazebo reference="main_base">
        <material>Gazebo/Blue</material>
    </gazebo>
    <gazebo reference="right_wheel_link">
        <material>Gazebo/Grey</material>
    </gazebo>
    <gazebo reference="left_wheel_link">
        <material>Gazebo/Grey</material>
    </gazebo>
    <gazebo reference="arm_base">
        <material>Gazebo/Orange</material>
    </gazebo>
    <gazebo reference="fore_arm">
        <material>Gazebo/Yellow</material>
    </gazebo>
    <gazebo reference="hand">
        <material>Gazebo/Orange</material>
    </gazebo>
    <gazebo reference="caster_wheel_link">
        <material>Gazebo/Grey</material>
        <mu1 value="0.1" />
        <mu2 value="0.1" />
    </gazebo>

    <gazebo>
        <plugin name="gazebo_ros_diff_drive" filename="libgazebo_ros_diff_drive.so">
            <!-- Update rate in Hz -->
            <update_rate>50</update_rate>

            <!-- wheels -->
            <left_joint>base_left_wheel_joint</left_joint>
            <right_joint>base_right_wheel_joint</right_joint>
            
            <max_wheel_torque>20</max_wheel_torque>
            <max_wheel_acceleration>2.0</max_wheel_acceleration>

            <command_topic>cmd_vel</command_topic>

            <!-- kinematics -->
            <wheel_separation>${main_base_width + wheel_length}</wheel_separation>
            <wheel_diameter>${2*wheel_radius}</wheel_diameter>

            <!-- output -->
            <publish_odom>true</publish_odom>
            <publish_odom_tf>true</publish_odom_tf>
            <publish_wheel_tf>true</publish_wheel_tf>

            <odometry_topic>odom</odometry_topic>
            <odometry_frame>odom</odometry_frame>
            <robot_base_frame>base_footprint</robot_base_frame>
        </plugin>
    </gazebo>

</robot>